// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPNJv9mdTuvQ6XVbvCNCaRQb-coh80tw',
    appId: '1:678018125735:web:d5eb00d74f72a35e297082',
    messagingSenderId: '678018125735',
    projectId: 'lab3-4b4d9',
    authDomain: 'lab3-4b4d9.firebaseapp.com',
    storageBucket: 'lab3-4b4d9.firebasestorage.app',
    measurementId: 'G-YF6M0FSEC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUyo0j9JZq7ZO6jl0kql_lkps1LA8k94',
    appId: '1:678018125735:android:b9f9da895955db71297082',
    messagingSenderId: '678018125735',
    projectId: 'lab3-4b4d9',
    storageBucket: 'lab3-4b4d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtBllTzNy9S9zLRhEkbEzQrR37CiDAhs',
    appId: '1:678018125735:ios:f5a1a1312e18c038297082',
    messagingSenderId: '678018125735',
    projectId: 'lab3-4b4d9',
    storageBucket: 'lab3-4b4d9.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtBllTzNy9S9zLRhEkbEzQrR37CiDAhs',
    appId: '1:678018125735:ios:f5a1a1312e18c038297082',
    messagingSenderId: '678018125735',
    projectId: 'lab3-4b4d9',
    storageBucket: 'lab3-4b4d9.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgPNJv9mdTuvQ6XVbvCNCaRQb-coh80tw',
    appId: '1:678018125735:web:35bc00280a2242c7297082',
    messagingSenderId: '678018125735',
    projectId: 'lab3-4b4d9',
    authDomain: 'lab3-4b4d9.firebaseapp.com',
    storageBucket: 'lab3-4b4d9.firebasestorage.app',
    measurementId: 'G-62BLQZT42L',
  );

}